## Assignment 5

#### Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

##### a) Addition of 2 in all the element b) Multiply 3 with all the elements c) Divide every element by 2

In [5]:
print("Original array:", arr)
print("Addition of 2:", arr + 2)
print("Multiplication by 3:", arr * 3)
print("Division by 2:", arr / 2)

Original array: [1 2 3 4 5]
Addition of 2: [3 4 5 6 7]
Multiplication by 3: [ 3  6  9 12 15]
Division by 2: [0.5 1.  1.5 2.  2.5]


#### Q.2 Questions on Basic NumPy Array: 
##### a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
##### b) Find the most frequent value and their indice(s) in the following arrays: 
###### i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
###### ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
arr = np.array([1,2,3,6,4,5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value:", most_frequent)
print("Indices:", np.where(x == most_frequent)[0])

Most frequent value: 1
Indices: [0 5 7 8 9]


In [8]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
print("Most frequent value:", most_frequent)
print("Indices:", np.where(y == most_frequent)[0])

Most frequent value: 1
Indices: [0 1 2]


#### Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: 
##### a) Access 1st row, 2nd column  
##### b) Access 3rd row, 1st column

In [9]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0, 1])
print(arr[2, 0])

20
70


#### Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute? 

In [11]:
arr = np.linspace(10,100,25)
print(arr)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [12]:
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Total elements:", arr.size)
print("Data type:", arr.dtype)
print("Total bytes:", arr.nbytes)

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200


In [13]:
transposed_arr = arr.reshape(5, 5)

print("Reshaped array:")
print(transposed_arr)

Reshaped array:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]


In [14]:
transposed_arr = arr.reshape(5, 5)

print("Transpose using .T:")
print(transposed_arr.T)

Transpose using .T:
[[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


#### Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [15]:
ucs420_samriddhi = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print(ucs420_samriddhi)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [17]:
print("Mean:", np.mean(ucs420_samriddhi))
print("Median:", np.median(ucs420_samriddhi))
print("Maximum:", np.max(ucs420_samriddhi))
print("Minimum:", np.min(ucs420_samriddhi))
print("Unique elements:", np.unique(ucs420_samriddhi))

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [18]:
reshaped_ucs420_samriddhi = ucs420_samriddhi.reshape(4, 3)

print("Reshaped array:")
print(reshaped_ucs420_samriddhi)

Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [20]:
resized_ucs420_samriddhi = np.resize(ucs420_samriddhi, (2, 3))

print("Resized array:")
print(resized_ucs420_samriddhi)

Resized array:
[[10 20 30]
 [40 50 60]]
